/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ColumnType {
  Bool = 0,
  Int64 = 1,
  Float64 = 2,
  TimestampNanos = 3,
  Date32 = 4,
  Bytes = 5,
  Embedding = 6
}
export const enum IndexKindSpec {
  Bitmap = 0,
  FmIndex = 1,
  Ann = 2
}
export interface ColumnSpec {
  id: number
  name: string
  ty: ColumnType
  primaryKey: boolean
  nullable: boolean
  /** Required when `ty == Embedding`. */
  embeddingDim?: number
}
export interface IndexSpec {
  name: string
  columnId: number
  kind: IndexKindSpec
}
export interface SchemaSpec {
  columns: Array<ColumnSpec>
  indexes: Array<IndexSpec>
}
/**
 * A single cell value. Only the field matching the column type is read; the
 * rest are ignored. `bytes` is raw; `text` is UTF-8 (use for `Bytes` columns
 * when the value is a string).
 */
export interface Cell {
  columnId: number
  int64?: bigint
  float64?: number
  boolean?: boolean
  text?: string
  bytes?: Buffer
  embedding?: Array<number>
}
export const enum ConditionKind {
  Pk = 0,
  BitmapEq = 1,
  RangeInt = 2,
  RangeF64 = 3,
  FmContains = 4,
  Ann = 5,
  PkInt64 = 6
}
/**
 * One predicate over the shared row-id space. Set the fields appropriate to
 * `kind`; unused fields are ignored. A `query` takes a conjunction (AND) of
 * these — the differentiator no SQL FTS pipeline can match.
 */
export interface ConditionSpec {
  kind: ConditionKind
  columnId: number
  int64Lo?: bigint
  int64Hi?: bigint
  float64Lo?: number
  float64Hi?: number
  text?: string
  embedding?: Array<number>
  k?: number
}
export interface RowJs {
  rowId: bigint
  cells: Array<Cell>
}
/** Phase 20.2: a typed column for bulk loading, wrapping JS typed-array data. */
export interface TypedColumn {
  columnId: number
  ty: ColumnType
  /** Raw data bytes (Int64 = N×8 LE, Float64 = N×8 LE, Bytes = N+1 offsets + values). */
  data: Buffer
  /** Optional validity bitmap (1 byte per row, 1=non-null). */
  validity?: Buffer
}
/**
 * An open MongrelDB multi-table database. Each table is accessible via
 * `table(name)`; SQL queries via `sql()`.
 */
export declare class Database {
  /** Create a fresh database at `path`. */
  static withPath(path: string): Database
  /** Open an existing database from disk. */
  static open(path: string): Database
  /** Create a new table with the given schema. */
  createTable(name: string, schema: SchemaSpec): bigint
  /** Drop a table by name. */
  dropTable(name: string): void
  /** Get a handle to a table by name for typed put/get/query operations. */
  getTable(name: string): TableHandle
  /** Alias for [`Database::get_table`] matching the spec's `database.table(name)`. */
  table(name: string): TableHandle
  /** Begin a cross-table transaction (stage puts/deletes, then `commit`). */
  begin(): Transaction
  /** The current reader-visible epoch — the database-wide snapshot point. */
  snapshotEpoch(): bigint
  /** List all live table names. */
  tableNames(): Array<string>
  /** Run a cross-table SQL query. Returns Arrow IPC bytes. */
  sql(sql: string): Promise<Buffer>
  /** Flush + release. Optional — the `Database` also drops on GC. */
  close(): void
  /**
   * Create a fresh encrypted database (page-level AES-256-GCM; the database
   * KEK is derived from `passphrase` via Argon2id + HKDF).
   */
  static createEncrypted(path: string, passphrase: string): Database
  /** Open an existing encrypted database with its passphrase. */
  static openEncrypted(path: string, passphrase: string): Database
}
/** A handle to one table inside a [`Database`]. */
export declare class TableHandle {
  /** Upsert one row. Returns the row id. */
  put(cells: Array<Cell>): bigint
  /** Group-commit this table's pending writes. */
  commit(): bigint
  /** Flush: commit + drain memtable to a sorted run. */
  flush(): bigint
  /** Live row count (O(1)). */
  count(): bigint
  /** Point read by row id. */
  get(rowId: bigint): RowJs | null
  /** Point read by a text primary key. */
  getByPkText(text: string): RowJs | null
  /** Point read by an Int64 primary key. */
  getByPkInt64(value: bigint): RowJs | null
  /** Delete a row by storage row id. */
  delete(rowId: bigint): void
  /** Delete the first row matching a text primary key. */
  deleteByPkText(text: string): void
  /** Delete the first row matching an Int64 primary key. */
  deleteByPkInt64(value: bigint): void
  /** Hybrid index query. */
  query(conditions: Array<ConditionSpec>): Array<RowJs>
  /** Insert a batch of rows in one call. Returns the new row ids in order. */
  putBatch(rows: Array<Array<Cell>>): Array<bigint>
  /**
   * Fastest ingest path: bulk-load typed columns (Int64/Float64/Bool) in one
   * shot, bypassing the per-cell `Value` enum. Returns the commit epoch.
   * Bytes/Embedding columns are not supported here — use `putBatch`.
   */
  bulkLoadTyped(columns: Array<TypedColumn>): bigint
  /**
   * Hybrid index query returning the matching rows as Arrow IPC bytes
   * (columnar, zero-copy on the JS side). Requires at least one condition —
   * use `Database.sql` for full scans.
   */
  queryArrow(conditions: Array<ConditionSpec>): Buffer
  putAsync(cells: Array<Cell>): Promise<bigint>
  commitAsync(): Promise<bigint>
  countAsync(): Promise<bigint>
  getAsync(rowId: bigint): Promise<RowJs | null>
  queryAsync(conditions: Array<ConditionSpec>): Promise<Array<RowJs>>
  flushAsync(): Promise<bigint>
  queryArrowAsync(conditions: Array<ConditionSpec>): Promise<Buffer>
}
/**
 * A cross-table transaction (P5.2). Stage puts/deletes across tables; commit
 * atomically. On conflict, `commit` throws a `ConflictError`.
 */
export declare class Transaction {
  constructor(db: Database)
  /** Stage a put on `table`. */
  put(table: string, cells: Array<Cell>): void
  /** Stage a delete of `row_id` on `table`. */
  delete(table: string, rowId: bigint): void
  /**
   * Commit all staged ops atomically. Returns the commit epoch.
   * Throws `ConflictError` on write-write conflict (retryable).
   */
  commit(): bigint
  /**
   * Commit off the JS event loop (the durability fsync runs on the NAPI
   * blocking pool). Throws `ConflictError` on write-write conflict.
   */
  commitAsync(): Promise<bigint>
  /** Discard all staged ops. */
  rollback(): void
  /**
   * Scope subsequent ops to `table` via a `TxnTable`, so the table name
   * isn't repeated on every `put`/`delete`. Pure sugar over the flat
   * `put(table, …)` / `delete(table, …)` API — the sub-handle stages into
   * THIS transaction, and this transaction's `commit`/`rollback` still drive
   * durability.
   */
  table(name: string): TxnTable
}
/**
 * A table-scoped view of a [`Transaction`] (returned by `transaction.table()`).
 * Stages `put`/`delete` for its bound table into the parent transaction; the
 * parent's `commit`/`rollback` still apply.
 */
export declare class TxnTable {
  /** Stage a put on this table. */
  put(cells: Array<Cell>): void
  /** Stage a batch of puts on this table. */
  putBatch(rows: Array<Array<Cell>>): void
  /** Stage a delete of `row_id` on this table. */
  delete(rowId: bigint): void
}
/**
 * Opt-in write micro-batching over one table. Writes are **not durable until
 * flush** — the contract is the opposite of `put()`.
 */
export declare class WriteBuffer {
  /** Create a new WriteBuffer over a table. `threshold` rows trigger an auto-flush. */
  constructor(table: TableHandle, threshold?: number | undefined | null)
  /**
   * Buffer a write (not durable until `flush`). Auto-flushes when the
   * threshold is reached, returning the new row id.
   */
  put(cells: Array<Cell>): bigint | null
  /** Flush all buffered writes (durable after this call). Returns the new epoch. */
  flush(): bigint
}
/**
 * A daemon-backed database connection (Phase 19.4). Routes put/get/count/
 * query/commit to a `mongreldb-server` instance over HTTP. Multiple Node
 * processes can share one warm cache this way.
 */
export declare class RemoteDatabase {
  /** Connect to a `mongreldb-server` at `url` (e.g. `http://127.0.0.1:8453`). */
  constructor(url: string)
  health(): string
  tableNames(): Array<string>
  count(table: string): number
  sql(sql: string): Buffer
  commit(table: string): bigint
}
