/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'mongreldb.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.android-arm64.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'mongreldb.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.android-arm-eabi.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'mongreldb.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'mongreldb.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'mongreldb.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'mongreldb.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./mongreldb.darwin-universal.node')
      } else {
        nativeBinding = require('@visorcraft/mongreldb-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'mongreldb.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.darwin-x64.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'mongreldb.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.darwin-arm64.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'mongreldb.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./mongreldb.freebsd-x64.node')
      } else {
        nativeBinding = require('@visorcraft/mongreldb-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-x64-musl.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mongreldb.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mongreldb.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@visorcraft/mongreldb-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'mongreldb.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mongreldb.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@visorcraft/mongreldb-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { buildInfo, minhashMemberHashV1, ColumnType, IndexKindSpec, AnnQuantizationSpec, IndexBuildPolicyJs, ConditionKind, Database, NativeCancelOutcome, NativeSqlQuery, TableHandle, Transaction, TxnTable, WriteBuffer, RemoteDatabase, NativeRemoteSqlQuery } = nativeBinding

module.exports.buildInfo = buildInfo
module.exports.minhashMemberHashV1 = minhashMemberHashV1
module.exports.ColumnType = ColumnType
module.exports.IndexKindSpec = IndexKindSpec
module.exports.AnnQuantizationSpec = AnnQuantizationSpec
module.exports.IndexBuildPolicyJs = IndexBuildPolicyJs
module.exports.ConditionKind = ConditionKind
module.exports.Database = Database
module.exports.NativeCancelOutcome = NativeCancelOutcome
module.exports.NativeSqlQuery = NativeSqlQuery
module.exports.TableHandle = TableHandle
module.exports.Transaction = Transaction
module.exports.TxnTable = TxnTable
module.exports.WriteBuffer = WriteBuffer
module.exports.RemoteDatabase = RemoteDatabase
module.exports.NativeRemoteSqlQuery = NativeRemoteSqlQuery
