//! Native Node.js addon for MongrelDB via NAPI — the better-sqlite3 model:
//! in-process, zero-HTTP-latency, sub-millisecond single-row writes.
//!
//! This crate exposes a **typed object/method interface** (not SQL): `Database`,
//! `put`, `get`, `commit`, `flush`, `count`, and a hybrid `query` that composes
//! the six row-id-space index primitives. TypeScript types are generated by
//! `@napi-rs/cli` at build time (`napi build`).
//!
//! Build (requires Node.js + `@napi-rs/cli`):
//!   cd crates/mongreldb-node && napi build --release --platform
//! Produces `mongreldb.<platform>.node` + `index.d.ts`.
//!
//! Row ids / counts / epochs cross the FFI as `BigInt` (lossless u64). Cross-
//! table SQL is also available via `Database.sql` (Arrow IPC results); the
//! typed object API stays the zero-SQL fast path for single-table ops.

#![deny(clippy::all)]

use mongreldb_core::query::{Condition, Query};
use mongreldb_core::schema::{ColumnDef, ColumnFlags, IndexDef, IndexKind, Schema, TypeId};
use mongreldb_core::{RowId, Value};
use napi::bindgen_prelude::{BigInt, Buffer};
use napi_derive::napi;
use std::sync::Arc;

/// Map core errors to NAPI with stable category prefixes so the JS wrapper can
/// recognize retryable conflicts (`__CONFLICT__:`) and missing entities
/// (`__NOT_FOUND__:`).
fn to_napi(e: mongreldb_core::MongrelError) -> napi::Error {
    let msg = match &e {
        mongreldb_core::MongrelError::Conflict(msg) => format!("__CONFLICT__:{msg}"),
        mongreldb_core::MongrelError::NotFound(msg) => format!("__NOT_FOUND__:{msg}"),
        _ => format!("{e:?}"),
    };
    napi::Error::new(napi::Status::GenericFailure, msg)
}

/// Map a transaction-commit result to JS, preserving conflict categories.
fn commit_result_to_napi(
    result: mongreldb_core::Result<mongreldb_core::Epoch>,
) -> napi::Result<BigInt> {
    result.map(|epoch| BigInt::from(epoch.0)).map_err(to_napi)
}

/// Convert a JS `BigInt` to `i64`, rejecting out-of-range values instead of
/// silently truncating.
fn bigint_to_i64(b: &BigInt) -> napi::Result<i64> {
    let (val, lossless) = b.get_i64();
    if !lossless {
        return Err(napi::Error::new(
            napi::Status::InvalidArg,
            "BigInt out of i64 range",
        ));
    }
    Ok(val)
}

/// Convert a JS `BigInt` to `u64`, rejecting out-of-range values (e.g. negative
/// or too-large row ids) instead of silently wrapping.
fn bigint_to_u64(b: &BigInt) -> napi::Result<u64> {
    let (negative, val, lossless) = b.get_u64();
    if negative || !lossless {
        return Err(napi::Error::new(
            napi::Status::InvalidArg,
            "BigInt out of u64 range",
        ));
    }
    Ok(val)
}

// ── schema ────────────────────────────────────────────────────────────────

#[napi]
pub enum ColumnType {
    Bool,
    Int64,
    Float64,
    TimestampNanos,
    Date32,
    Bytes,
    Embedding,
}

#[napi]
pub enum IndexKindSpec {
    Bitmap,
    FmIndex,
    Ann,
}

#[napi(object)]
pub struct ColumnSpec {
    pub id: u16,
    pub name: String,
    pub ty: ColumnType,
    pub primary_key: bool,
    pub nullable: bool,
    /// Required when `ty == Embedding`.
    pub embedding_dim: Option<u32>,
    /// Optional default value for schema-evolution back-fill. Currently only
    /// validated; applying defaults to existing rows is not yet implemented.
    pub default_value: Option<Cell>,
}

#[napi(object)]
pub struct IndexSpec {
    pub name: String,
    pub column_id: u16,
    pub kind: IndexKindSpec,
}

#[napi(object)]
pub struct SchemaSpec {
    pub columns: Vec<ColumnSpec>,
    pub indexes: Vec<IndexSpec>,
}

fn to_type_id(ty: &ColumnType, embedding_dim: Option<u32>) -> napi::Result<TypeId> {
    Ok(match ty {
        ColumnType::Bool => TypeId::Bool,
        ColumnType::Int64 => TypeId::Int64,
        ColumnType::Float64 => TypeId::Float64,
        ColumnType::TimestampNanos => TypeId::TimestampNanos,
        ColumnType::Date32 => TypeId::Date32,
        ColumnType::Bytes => TypeId::Bytes,
        ColumnType::Embedding => TypeId::Embedding {
            dim: embedding_dim.ok_or_else(|| {
                napi::Error::new(
                    napi::Status::InvalidArg,
                    "embedding_dim is required for Embedding columns",
                )
            })?,
        },
    })
}

fn build_schema(spec: SchemaSpec) -> napi::Result<Schema> {
    let columns = spec
        .columns
        .into_iter()
        .map(|c| {
            let mut f = ColumnFlags::empty();
            if c.primary_key {
                f = f.with(ColumnFlags::PRIMARY_KEY);
            }
            if c.nullable {
                f = f.with(ColumnFlags::NULLABLE);
            }
            Ok::<ColumnDef, napi::Error>(ColumnDef {
                id: c.id,
                name: c.name,
                ty: to_type_id(&c.ty, c.embedding_dim)?,
                flags: f,
            })
        })
        .collect::<napi::Result<Vec<_>>>()?;
    let indexes = spec
        .indexes
        .into_iter()
        .map(|i| IndexDef {
            name: i.name,
            column_id: i.column_id,
            kind: match i.kind {
                IndexKindSpec::Bitmap => IndexKind::Bitmap,
                IndexKindSpec::FmIndex => IndexKind::FmIndex,
                IndexKindSpec::Ann => IndexKind::Ann,
            },
        })
        .collect();
    Ok(Schema {
        schema_id: 1,
        columns,
        indexes,
        colocation: Vec::new(),
    })
}

// ── values ────────────────────────────────────────────────────────────────

/// A single cell value. Only the field matching the column type is read; the
/// rest are ignored. `bytes` is raw; `text` is UTF-8 (use for `Bytes` columns
/// when the value is a string).
#[napi(object)]
pub struct Cell {
    pub column_id: u16,
    pub int64: Option<BigInt>,
    pub float64: Option<f64>,
    pub boolean: Option<bool>,
    pub text: Option<String>,
    pub bytes: Option<Buffer>,
    pub embedding: Option<Vec<f64>>,
}

impl Cell {
    fn empty(column_id: u16) -> Self {
        Self {
            column_id,
            int64: None,
            float64: None,
            boolean: None,
            text: None,
            bytes: None,
            embedding: None,
        }
    }

    fn to_value(&self, ty: TypeId) -> napi::Result<Value> {
        Ok(match ty {
            TypeId::Bool => Value::Bool(self.boolean.unwrap_or(false)),
            TypeId::Int64 | TypeId::TimestampNanos | TypeId::Date32 => {
                Value::Int64(
                    self.int64
                        .as_ref()
                        .map(bigint_to_i64)
                        .transpose()?
                        .unwrap_or(0),
                )
            }
            TypeId::Float64 => Value::Float64(self.float64.unwrap_or(0.0)),
            TypeId::Bytes => match &self.text {
                Some(s) => Value::Bytes(s.as_bytes().to_vec()),
                None => Value::Bytes(self.bytes.as_ref().map(|b| b.to_vec()).unwrap_or_default()),
            },
            TypeId::Embedding { .. } => {
                Value::Embedding(self.embedding.iter().flatten().map(|x| *x as f32).collect())
            }
            _ => Value::Null,
        })
    }
}

fn from_value(v: &Value, column_id: u16) -> Cell {
    let mut cell = Cell::empty(column_id);
    match v {
        Value::Null => {}
        Value::Bool(b) => cell.boolean = Some(*b),
        Value::Int64(n) => cell.int64 = Some(BigInt::from(*n)),
        Value::Float64(f) => cell.float64 = Some(*f),
        Value::Bytes(b) => match std::str::from_utf8(b) {
            Ok(s) => cell.text = Some(s.to_string()),
            Err(_) => cell.bytes = Some(Buffer::from(b.clone())),
        },
        Value::Embedding(e) => cell.embedding = Some(e.iter().map(|x| *x as f64).collect()),
    }
    cell
}

// ── query conditions ──────────────────────────────────────────────────────

#[napi]
pub enum ConditionKind {
    Pk,
    BitmapEq,
    RangeInt,
    RangeF64,
    FmContains,
    Ann,
    PkInt64,
}

/// One predicate over the shared row-id space. Set the fields appropriate to
/// `kind`; unused fields are ignored. A `query` takes a conjunction (AND) of
/// these — the differentiator no SQL FTS pipeline can match.
#[napi(object)]
pub struct ConditionSpec {
    pub kind: ConditionKind,
    pub column_id: u16,
    pub int64_lo: Option<BigInt>,
    pub int64_hi: Option<BigInt>,
    pub float64_lo: Option<f64>,
    pub float64_hi: Option<f64>,
    pub text: Option<String>,
    pub embedding: Option<Vec<f64>>,
    pub k: Option<u32>,
}

fn build_condition(spec: &ConditionSpec) -> napi::Result<Condition> {
    Ok(match spec.kind {
        ConditionKind::Pk => Condition::Pk(text_bytes(spec)?),
        ConditionKind::BitmapEq => Condition::BitmapEq {
            column_id: spec.column_id,
            value: text_bytes(spec)?,
        },
        ConditionKind::RangeInt => Condition::Range {
            column_id: spec.column_id,
            lo: spec
                .int64_lo
                .as_ref()
                .map(bigint_to_i64)
                .transpose()?
                .unwrap_or(i64::MIN),
            hi: spec
                .int64_hi
                .as_ref()
                .map(bigint_to_i64)
                .transpose()?
                .unwrap_or(i64::MAX),
        },
        ConditionKind::RangeF64 => Condition::RangeF64 {
            column_id: spec.column_id,
            lo: spec.float64_lo.unwrap_or(f64::NEG_INFINITY),
            lo_inclusive: true,
            hi: spec.float64_hi.unwrap_or(f64::INFINITY),
            hi_inclusive: true,
        },
        ConditionKind::FmContains => Condition::FmContains {
            column_id: spec.column_id,
            pattern: text_bytes(spec)?,
        },
        ConditionKind::Ann => Condition::Ann {
            column_id: spec.column_id,
            query: spec
                .embedding
                .clone()
                .ok_or_else(|| napi::Error::new(napi::Status::InvalidArg, "Ann needs embedding"))?
                .iter()
                .map(|x| *x as f32)
                .collect(),
            k: spec.k.unwrap_or(10) as usize,
        },
        ConditionKind::PkInt64 => Condition::Pk(
            bigint_to_i64(
                spec.int64_lo
                    .as_ref()
                    .ok_or_else(|| napi::Error::new(napi::Status::InvalidArg, "PkInt64 needs int64_lo"))?,
            )?
            .to_be_bytes()
            .to_vec(),
        ),
    })
}

fn text_bytes(spec: &ConditionSpec) -> napi::Result<Vec<u8>> {
    spec.text
        .as_ref()
        .map(|s| s.as_bytes().to_vec())
        .ok_or_else(|| napi::Error::new(napi::Status::InvalidArg, "expected `text`"))
}

#[napi(object)]
pub struct RowJs {
    pub row_id: BigInt,
    pub cells: Vec<Cell>,
}

// ── multi-table Database + Table (P5.1) ───────────────────────────────────

use mongreldb_core::Database as CoreDatabase;

/// An open MongrelDB multi-table database. Each table is accessible via
/// `table(name)`; SQL queries via `sql()`.
#[napi]
pub struct Database {
    inner: Arc<CoreDatabase>,
    path: String,
}

/// A handle to one table inside a [`Database`].
#[napi]
pub struct TableHandle {
    db: Arc<CoreDatabase>,
    name: String,
}

fn cell_pairs_table(
    t: &mongreldb_core::Table,
    cells: Vec<Cell>,
) -> napi::Result<Vec<(u16, Value)>> {
    let schema = t.schema();
    cells
        .into_iter()
        .map(|c| {
            let ty = schema
                .columns
                .iter()
                .find(|cd| cd.id == c.column_id)
                .map(|cd| cd.ty)
                .unwrap_or(TypeId::Bytes);
            Ok((c.column_id, c.to_value(ty)?))
        })
        .collect()
}

fn row_to_js_table(t: &mongreldb_core::Table, row: &mongreldb_core::memtable::Row) -> RowJs {
    let schema = t.schema();
    let cells = schema
        .columns
        .iter()
        .map(|cd| {
            let v = row.columns.get(&cd.id).cloned().unwrap_or(Value::Null);
            from_value(&v, cd.id)
        })
        .collect();
    RowJs {
        row_id: BigInt::from(row.row_id.0),
        cells,
    }
}

#[napi]
impl Database {
    /// Create a fresh database at `path`.
    #[napi(factory)]
    pub fn with_path(path: String) -> napi::Result<Database> {
        let db = CoreDatabase::create(&path).map_err(to_napi)?;
        Ok(Database {
            inner: Arc::new(db),
            path,
        })
    }

    /// Open an existing database from disk.
    #[napi]
    pub fn open(path: String) -> napi::Result<Database> {
        let db = CoreDatabase::open(&path).map_err(to_napi)?;
        Ok(Database {
            inner: Arc::new(db),
            path,
        })
    }

    /// Create a new table with the given schema.
    #[napi]
    pub fn create_table(&self, name: String, schema: SchemaSpec) -> napi::Result<BigInt> {
        let s = build_schema(schema)?;
        let id = self.inner.create_table(&name, s).map_err(to_napi)?;
        Ok(BigInt::from(id))
    }

    /// Drop a table by name.
    #[napi]
    pub fn drop_table(&self, name: String) -> napi::Result<()> {
        self.inner.drop_table(&name).map_err(to_napi)
    }

    /// Get a handle to a table by name for typed put/get/query operations.
    #[napi]
    pub fn get_table(&self, name: String) -> napi::Result<TableHandle> {
        // Validate the table exists now; per-op calls re-resolve it by name.
        self.inner.table_id(&name).map_err(to_napi)?;
        Ok(TableHandle {
            db: Arc::clone(&self.inner),
            name,
        })
    }

    /// Alias for [`Database::get_table`] matching the spec's `database.table(name)`.
    #[napi]
    pub fn table(&self, name: String) -> napi::Result<TableHandle> {
        self.get_table(name)
    }

    /// Begin a cross-table transaction (stage puts/deletes, then `commit`).
    #[napi]
    pub fn begin(&self) -> Transaction {
        Transaction {
            db: Arc::clone(&self.inner),
            staging: Arc::new(parking_lot::Mutex::new(Vec::new())),
        }
    }

    /// The current reader-visible epoch — the database-wide snapshot point.
    #[napi]
    pub fn snapshot_epoch(&self) -> BigInt {
        BigInt::from(self.inner.visible_epoch().0)
    }

    /// List all live table names.
    #[napi]
    pub fn table_names(&self) -> Vec<String> {
        self.inner.table_names()
    }

    /// Add a column to an existing table. The column must be nullable or supply
    /// a default value so existing rows can be evolved safely.
    #[napi]
    pub fn add_column(&self, table: String, column: ColumnSpec) -> napi::Result<BigInt> {
        if !column.nullable && column.default_value.is_none() {
            return Err(napi::Error::new(
                napi::Status::InvalidArg,
                "non-null column added without default",
            ));
        }
        let handle = self.inner.table(&table).map_err(to_napi)?;
        let mut g = handle.lock();
        let ty = to_type_id(&column.ty, column.embedding_dim)?;
        // Core `add_column` always adds the column as nullable; enforcing a
        // non-null constraint with a default would require a full table rewrite,
        // which is not yet implemented. The validation above still rejects the
        // unsupported "non-null without default" case.
        let id = g.add_column(&column.name, ty).map_err(to_napi)?;
        Ok(BigInt::from(id as u64))
    }

    /// Verify database integrity. Returns a JSON-string summary.
    #[napi]
    pub fn check(&self) -> napi::Result<String> {
        let issues = self.inner.check();
        let mut tables: std::collections::HashMap<u64, serde_json::Value> =
            std::collections::HashMap::new();
        for issue in &issues {
            let entry = tables.entry(issue.table_id).or_insert_with(|| {
                serde_json::json!({
                    "table_id": issue.table_id,
                    "table_name": &issue.table_name,
                    "issue_count": 0,
                    "issues": [],
                })
            });
            entry["issue_count"] = serde_json::json!(entry["issue_count"].as_u64().unwrap_or(0) + 1);
            entry["issues"]
                .as_array_mut()
                .unwrap()
                .push(serde_json::json!({
                    "severity": &issue.severity,
                    "description": &issue.description,
                }));
        }
        let summary = serde_json::json!({
            "ok": issues.is_empty(),
            "tables": tables.values().collect::<Vec<_>>(),
        });
        Ok(summary.to_string())
    }

    /// Repair/quarantine corrupt tables. Returns a JSON-string summary.
    #[napi]
    pub fn doctor(&self) -> napi::Result<String> {
        let quarantined = self.inner.doctor().map_err(to_napi)?;
        let summary = serde_json::json!({
            "ok": quarantined.is_empty(),
            "quarantined": quarantined,
        });
        Ok(summary.to_string())
    }

    /// Return the path passed to `withPath` / `open`.
    #[napi]
    pub fn directory(&self) -> String {
        self.path.clone()
    }

    /// Run a cross-table SQL query. Returns Arrow IPC bytes.
    #[napi]
    pub async fn sql(&self, sql: String) -> napi::Result<Buffer> {
        let db = Arc::clone(&self.inner);
        let session = mongreldb_query::MongrelSession::open(db)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
        let batches = session
            .run(&sql)
            .await
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
        native_cols_to_ipc_from_batches(&batches)
    }

    /// Flush + release. Optional — the `Database` also drops on GC.
    #[napi]
    pub fn close(&self) -> napi::Result<()> {
        Ok(())
    }
}

/// Encrypted constructors. The `encryption` feature is **on by default**; build
/// with `--no-default-features` to omit it. Kept as a whole separate impl block
/// because a per-method `#[cfg]` inside a `#[napi] impl` would leave a dangling
/// `#[napi]` registration symbol when the feature is disabled.
#[cfg(feature = "encryption")]
#[napi]
impl Database {
    /// Create a fresh encrypted database (page-level AES-256-GCM; the database
    /// KEK is derived from `passphrase` via Argon2id + HKDF).
    #[napi(factory)]
    pub fn create_encrypted(path: String, passphrase: String) -> napi::Result<Database> {
        let db = CoreDatabase::create_encrypted(&path, &passphrase).map_err(to_napi)?;
        Ok(Database {
            inner: Arc::new(db),
            path,
        })
    }

    /// Open an existing encrypted database with its passphrase.
    #[napi]
    pub fn open_encrypted(path: String, passphrase: String) -> napi::Result<Database> {
        let db = CoreDatabase::open_encrypted(&path, &passphrase).map_err(to_napi)?;
        Ok(Database {
            inner: Arc::new(db),
            path,
        })
    }
}

fn native_cols_to_ipc_from_batches(
    batches: &[arrow::record_batch::RecordBatch],
) -> napi::Result<Buffer> {
    if batches.is_empty() {
        return Ok(Buffer::from(Vec::new()));
    }
    let schema = batches[0].schema();
    let mut buf = Vec::new();
    let mut writer = arrow::ipc::writer::FileWriter::try_new(&mut buf, schema.as_ref())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
    for b in batches {
        writer
            .write(b)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
    }
    writer
        .finish()
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
    drop(writer);
    Ok(Buffer::from(buf))
}

#[napi]
impl TableHandle {
    /// Upsert one row. Returns the row id.
    #[napi]
    pub fn put(&self, cells: Vec<Cell>) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let cols = cell_pairs_table(&g, cells)?;
        let rid = g.put(cols).map_err(to_napi)?;
        Ok(BigInt::from(rid.0))
    }

    /// Group-commit this table's pending writes.
    #[napi]
    pub fn commit(&self) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.commit().map(|e| BigInt::from(e.0)).map_err(to_napi)
    }

    /// Flush: commit + drain memtable to a sorted run.
    #[napi]
    pub fn flush(&self) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.flush().map(|e| BigInt::from(e.0)).map_err(to_napi)
    }

    /// Live row count (O(1)).
    #[napi]
    pub fn count(&self) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let g = handle.lock();
        Ok(BigInt::from(g.count()))
    }

    /// Point read by row id.
    #[napi]
    pub fn get(&self, row_id: BigInt) -> napi::Result<Option<RowJs>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let g = handle.lock();
        let snap = g.snapshot();
        Ok(g.get(RowId(bigint_to_u64(&row_id)?), snap)
            .map(|r| row_to_js_table(&g, &r)))
    }

    /// Point read by a text primary key.
    #[napi]
    pub fn get_by_pk_text(&self, text: String) -> napi::Result<Option<RowJs>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let q = Query::pk(text.into_bytes());
        let rows = g.query_cached(&q).map_err(to_napi)?;
        Ok(rows.first().map(|r| row_to_js_table(&g, r)))
    }

    /// Point read by an Int64 primary key.
    #[napi]
    pub fn get_by_pk_int64(&self, value: BigInt) -> napi::Result<Option<RowJs>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let q = Query::pk(bigint_to_i64(&value)?.to_be_bytes().to_vec());
        let rows = g.query_cached(&q).map_err(to_napi)?;
        Ok(rows.first().map(|r| row_to_js_table(&g, r)))
    }

    /// Delete a row by storage row id.
    #[napi]
    pub fn delete(&self, row_id: BigInt) -> napi::Result<()> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.delete(RowId(bigint_to_u64(&row_id)?)).map_err(to_napi)
    }

    /// Delete the first row matching a text primary key.
    #[napi]
    pub fn delete_by_pk_text(&self, text: String) -> napi::Result<()> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let q = Query::pk(text.into_bytes());
        let rows = g.query_cached(&q).map_err(to_napi)?;
        if let Some(r) = rows.first() {
            g.delete(r.row_id).map_err(to_napi)?;
        }
        Ok(())
    }

    /// Delete the first row matching an Int64 primary key.
    #[napi]
    pub fn delete_by_pk_int64(&self, value: BigInt) -> napi::Result<()> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let q = Query::pk(bigint_to_i64(&value)?.to_be_bytes().to_vec());
        let rows = g.query_cached(&q).map_err(to_napi)?;
        if let Some(r) = rows.first() {
            g.delete(r.row_id).map_err(to_napi)?;
        }
        Ok(())
    }

    /// Hybrid index query.
    #[napi]
    pub fn query(&self, conditions: Vec<ConditionSpec>) -> napi::Result<Vec<RowJs>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let mut q = Query::new();
        for c in &conditions {
            q = q.and(build_condition(c)?);
        }
        let rows = g.query_cached(&q).map_err(to_napi)?;
        Ok(rows.iter().map(|r| row_to_js_table(&g, r)).collect())
    }

    /// Insert a batch of rows in one call. Returns the new row ids in order.
    #[napi]
    pub fn put_batch(&self, rows: Vec<Vec<Cell>>) -> napi::Result<Vec<BigInt>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let mut batch = Vec::with_capacity(rows.len());
        for cells in rows {
            batch.push(cell_pairs_table(&g, cells)?);
        }
        let rids = g.put_batch(batch).map_err(to_napi)?;
        Ok(rids.into_iter().map(|r| BigInt::from(r.0)).collect())
    }

    /// Fastest ingest path: bulk-load typed columns (Int64/Float64/Bool) in one
    /// shot, bypassing the per-cell `Value` enum. Returns the commit epoch.
    /// Bytes/Embedding columns are not supported here — use `putBatch`.
    #[napi]
    pub fn bulk_load_typed(&self, columns: Vec<TypedColumn>) -> napi::Result<BigInt> {
        let native = columns
            .into_iter()
            .map(|c| c.into_native())
            .collect::<napi::Result<Vec<_>>>()?;
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.bulk_load_columns(native)
            .map(|e| BigInt::from(e.0))
            .map_err(to_napi)
    }

    /// Hybrid index query returning the matching rows as Arrow IPC bytes
    /// (columnar, zero-copy on the JS side). Requires at least one condition —
    /// use `Database.sql` for full scans.
    #[napi]
    pub fn query_arrow(&self, conditions: Vec<ConditionSpec>) -> napi::Result<Buffer> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        query_arrow_inner(&mut g, &conditions)
    }

    // ── async variants ──

    #[napi]
    pub async fn put_async(&self, cells: Vec<Cell>) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<BigInt> {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            let cols = cell_pairs_table(&g, cells)?;
            let rid = g.put(cols).map_err(to_napi)?;
            Ok(BigInt::from(rid.0))
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn commit_async(&self) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            g.commit().map(|e| BigInt::from(e.0)).map_err(to_napi)
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn count_async(&self) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || {
            let handle = db.table(&name).map_err(to_napi)?;
            let g = handle.lock();
            Ok(BigInt::from(g.count()))
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn get_async(&self, row_id: BigInt) -> napi::Result<Option<RowJs>> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        let row_id_u64 = bigint_to_u64(&row_id)?;
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<Option<RowJs>> {
            let handle = db.table(&name).map_err(to_napi)?;
            let g = handle.lock();
            let snap = g.snapshot();
            Ok(g.get(RowId(row_id_u64), snap)
                .map(|r| row_to_js_table(&g, &r)))
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn query_async(&self, conditions: Vec<ConditionSpec>) -> napi::Result<Vec<RowJs>> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<Vec<RowJs>> {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            let mut q = Query::new();
            for c in &conditions {
                q = q.and(build_condition(c)?);
            }
            let rows = g.query_cached(&q).map_err(to_napi)?;
            Ok(rows.iter().map(|r| row_to_js_table(&g, r)).collect())
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn flush_async(&self) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            g.flush().map(|e| BigInt::from(e.0)).map_err(to_napi)
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn query_arrow_async(&self, conditions: Vec<ConditionSpec>) -> napi::Result<Buffer> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<Buffer> {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            query_arrow_inner(&mut g, &conditions)
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }
}

/// Shared body for `query_arrow` / `query_arrow_async`: resolve the conditions
/// to native columns under a fresh snapshot and serialize them to Arrow IPC.
fn query_arrow_inner(
    g: &mut mongreldb_core::Table,
    conditions: &[ConditionSpec],
) -> napi::Result<Buffer> {
    if conditions.is_empty() {
        return Err(napi::Error::new(
            napi::Status::InvalidArg,
            "queryArrow requires at least one condition; use Database.sql for full scans",
        ));
    }
    let mut conds = Vec::with_capacity(conditions.len());
    for c in conditions {
        conds.push(build_condition(c)?);
    }
    let snap = g.snapshot();
    let proj: Vec<u16> = g.schema().columns.iter().map(|c| c.id).collect();
    let cols = g
        .query_columns_native(&conds, Some(&proj), snap)
        .map_err(to_napi)?;
    match cols {
        Some(cols) => Ok(Buffer::from(native_cols_to_ipc(&cols, g.schema())?)),
        None => Ok(Buffer::from(Vec::new())),
    }
}

/// A cross-table transaction (P5.2). Stage puts/deletes across tables; commit
/// atomically. On conflict, `commit` throws a `ConflictError`.
#[napi]
pub struct Transaction {
    db: Arc<CoreDatabase>,
    // Interior mutability so every method takes `&self` (NAPI async can't take
    // `&mut self`); `Arc` so a `TxnTable` sub-handle can stage into the same
    // buffer, and the handle itself is cheap to share.
    staging: Arc<parking_lot::Mutex<Vec<(String, TxnOp)>>>,
}

enum TxnOp {
    Put(Vec<(u16, Value)>),
    Delete(RowId),
}

#[napi]
impl Transaction {
    #[napi(constructor)]
    pub fn new(db: &Database) -> Self {
        Self {
            db: Arc::clone(&db.inner),
            staging: Arc::new(parking_lot::Mutex::new(Vec::new())),
        }
    }

    /// Stage a put on `table`.
    #[napi]
    pub fn put(&self, table: String, cells: Vec<Cell>) -> napi::Result<()> {
        let handle = self.db.table(&table).map_err(to_napi)?;
        let g = handle.lock();
        let cols = cell_pairs_table(&g, cells)?;
        drop(g);
        self.staging.lock().push((table, TxnOp::Put(cols)));
        Ok(())
    }

    /// Stage a delete of `row_id` on `table`.
    #[napi]
    pub fn delete(&self, table: String, row_id: BigInt) -> napi::Result<()> {
        self.staging
            .lock()
            .push((table, TxnOp::Delete(RowId(bigint_to_u64(&row_id)?))));
        Ok(())
    }

    /// Commit all staged ops atomically. Returns the commit epoch.
    /// Throws `ConflictError` on write-write conflict (retryable).
    #[napi]
    pub fn commit(&self) -> napi::Result<BigInt> {
        let stage = std::mem::take(&mut *self.staging.lock());
        commit_result_to_napi(apply_txn(&self.db, &stage))
    }

    /// Commit off the JS event loop (the durability fsync runs on the NAPI
    /// blocking pool). Throws `ConflictError` on write-write conflict.
    #[napi]
    pub async fn commit_async(&self) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let stage = std::mem::take(&mut *self.staging.lock());
        napi::bindgen_prelude::spawn_blocking(move || commit_result_to_napi(apply_txn(&db, &stage)))
            .await
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    /// Discard all staged ops.
    #[napi]
    pub fn rollback(&self) {
        self.staging.lock().clear();
    }

    /// Scope subsequent ops to `table` via a `TxnTable`, so the table name
    /// isn't repeated on every `put`/`delete`. Pure sugar over the flat
    /// `put(table, …)` / `delete(table, …)` API — the sub-handle stages into
    /// THIS transaction, and this transaction's `commit`/`rollback` still drive
    /// durability.
    #[napi]
    pub fn table(&self, name: String) -> napi::Result<TxnTable> {
        // Validate the table exists up front (matches Database::get_table).
        self.db.table(&name).map_err(to_napi)?;
        Ok(TxnTable {
            db: Arc::clone(&self.db),
            staging: Arc::clone(&self.staging),
            table: name,
        })
    }
}

/// A table-scoped view of a [`Transaction`] (returned by `transaction.table()`).
/// Stages `put`/`delete` for its bound table into the parent transaction; the
/// parent's `commit`/`rollback` still apply.
#[napi]
pub struct TxnTable {
    db: Arc<CoreDatabase>,
    staging: Arc<parking_lot::Mutex<Vec<(String, TxnOp)>>>,
    table: String,
}

#[napi]
impl TxnTable {
    /// Stage a put on this table.
    #[napi]
    pub fn put(&self, cells: Vec<Cell>) -> napi::Result<()> {
        let cols = {
            let handle = self.db.table(&self.table).map_err(to_napi)?;
            let g = handle.lock();
            cell_pairs_table(&g, cells)?
        };
        self.staging
            .lock()
            .push((self.table.clone(), TxnOp::Put(cols)));
        Ok(())
    }

    /// Stage a batch of puts on this table.
    #[napi]
    pub fn put_batch(&self, rows: Vec<Vec<Cell>>) -> napi::Result<()> {
        let staged = {
            let handle = self.db.table(&self.table).map_err(to_napi)?;
            let g = handle.lock();
            rows.into_iter()
                .map(|cells| cell_pairs_table(&g, cells))
                .collect::<napi::Result<Vec<_>>>()?
        };
        let mut buf = self.staging.lock();
        for cols in staged {
            buf.push((self.table.clone(), TxnOp::Put(cols)));
        }
        Ok(())
    }

    /// Stage a delete of `row_id` on this table.
    #[napi]
    pub fn delete(&self, row_id: BigInt) -> napi::Result<()> {
        self.staging
            .lock()
            .push((self.table.clone(), TxnOp::Delete(RowId(bigint_to_u64(&row_id)?))));
        Ok(())
    }
}

/// Replay staged ops into a fresh core transaction and commit atomically.
fn apply_txn(
    db: &CoreDatabase,
    stage: &[(String, TxnOp)],
) -> mongreldb_core::Result<mongreldb_core::Epoch> {
    let mut tx = db.begin();
    for (table, op) in stage {
        match op {
            TxnOp::Put(cells) => tx.put(table, cells.clone())?,
            TxnOp::Delete(rid) => tx.delete(table, *rid)?,
        }
    }
    tx.commit()
}

/// Phase 20.2: a typed column for bulk loading, wrapping JS typed-array data.
#[napi(object)]
pub struct TypedColumn {
    pub column_id: u16,
    pub ty: ColumnType,
    /// Raw data bytes (Int64 = N×8 LE, Float64 = N×8 LE, Bytes = N+1 offsets + values).
    pub data: Buffer,
    /// Optional validity bitmap (1 byte per row, 1=non-null).
    pub validity: Option<Buffer>,
}

impl TypedColumn {
    fn into_native(self) -> napi::Result<(u16, mongreldb_core::columnar::NativeColumn)> {
        let n = match self.ty {
            ColumnType::Int64
            | ColumnType::Float64
            | ColumnType::TimestampNanos
            | ColumnType::Date32 => self.data.len() / 8,
            ColumnType::Bool => self.data.len(),
            ColumnType::Bytes | ColumnType::Embedding => {
                return Err(napi::Error::new(
                    napi::Status::InvalidArg,
                    "Bytes/Embedding columns not supported in bulk_load_typed; use bulk_load",
                ))
            }
        };
        let validity = self
            .validity
            .map(|b| b.to_vec())
            .unwrap_or_else(|| vec![0xFF; n.div_ceil(8)]);
        let col = match self.ty {
            ColumnType::Int64 | ColumnType::TimestampNanos | ColumnType::Date32 => {
                let data = bytemuck::cast_slice::<_, i64>(&self.data).to_vec();
                mongreldb_core::columnar::NativeColumn::Int64 { data, validity }
            }
            ColumnType::Float64 => {
                let data = bytemuck::cast_slice::<_, f64>(&self.data).to_vec();
                mongreldb_core::columnar::NativeColumn::Float64 { data, validity }
            }
            ColumnType::Bool => mongreldb_core::columnar::NativeColumn::Bool {
                data: self.data.to_vec(),
                validity,
            },
            _ => unreachable!(),
        };
        Ok((self.column_id, col))
    }
}

/// Opt-in write micro-batching over one table. Writes are **not durable until
/// flush** — the contract is the opposite of `put()`.
#[napi]
pub struct WriteBuffer {
    db: Arc<CoreDatabase>,
    table_name: String,
    buffer: Vec<Vec<(u16, Value)>>,
    threshold: usize,
}

#[napi]
impl WriteBuffer {
    /// Create a new WriteBuffer over a table. `threshold` rows trigger an auto-flush.
    #[napi(constructor)]
    pub fn new(table: &TableHandle, threshold: Option<u32>) -> Self {
        Self {
            db: Arc::clone(&table.db),
            table_name: table.name.clone(),
            buffer: Vec::new(),
            threshold: threshold.unwrap_or(1000) as usize,
        }
    }

    /// Buffer a write (not durable until `flush`). Auto-flushes when the
    /// threshold is reached, returning the new row id.
    #[napi]
    pub fn put(&mut self, cells: Vec<Cell>) -> napi::Result<Option<BigInt>> {
        let pair = {
            let handle = self.db.table(&self.table_name).map_err(to_napi)?;
            let g = handle.lock();
            cell_pairs_table(&g, cells)?
        };
        self.buffer.push(pair);
        if self.buffer.len() >= self.threshold {
            let n = self.flush()?;
            Ok(Some(n))
        } else {
            Ok(None)
        }
    }

    /// Flush all buffered writes (durable after this call). Returns the new epoch.
    #[napi]
    pub fn flush(&mut self) -> napi::Result<BigInt> {
        if self.buffer.is_empty() {
            let handle = self.db.table(&self.table_name).map_err(to_napi)?;
            return Ok(BigInt::from(handle.lock().current_epoch().0));
        }
        let batch = std::mem::take(&mut self.buffer);
        let handle = self.db.table(&self.table_name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.put_batch(batch).map_err(to_napi)?;
        let epoch = g.commit().map_err(to_napi)?;
        Ok(BigInt::from(epoch.0))
    }
}

fn arrow_from_native(
    ty: mongreldb_core::schema::TypeId,
    col: &mongreldb_core::columnar::NativeColumn,
) -> napi::Result<arrow::array::ArrayRef> {
    use mongreldb_core::columnar::NativeColumn;
    use mongreldb_core::schema::TypeId;
    Ok(match (ty, col) {
        (
            TypeId::Int64 | TypeId::TimestampNanos | TypeId::Date32,
            NativeColumn::Int64 { data, validity },
        ) => {
            let buf: arrow::buffer::ScalarBuffer<_> = data.clone().into();
            let nulls = validity_to_nulls(validity, data.len());
            Arc::new(arrow::array::Int64Array::new(buf, nulls))
        }
        (TypeId::Float64, NativeColumn::Float64 { data, validity }) => {
            let buf: arrow::buffer::ScalarBuffer<_> = data.clone().into();
            let nulls = validity_to_nulls(validity, data.len());
            Arc::new(arrow::array::Float64Array::new(buf, nulls))
        }
        (TypeId::Bool, NativeColumn::Bool { data, validity }) => {
            let mut b = arrow::array::BooleanBuilder::with_capacity(data.len());
            for (i, &v) in data.iter().enumerate() {
                if bit_set(validity, i) {
                    b.append_value(v != 0);
                } else {
                    b.append_null();
                }
            }
            Arc::new(b.finish())
        }
        (
            _,
            NativeColumn::Bytes {
                offsets,
                values,
                validity,
            },
        ) => {
            let n = offsets.len().saturating_sub(1);
            let mut b = arrow::array::StringBuilder::with_capacity(n, values.len());
            for i in 0..n {
                if bit_set(validity, i) {
                    let lo = offsets[i] as usize;
                    let hi = offsets[i + 1] as usize;
                    b.append_value(String::from_utf8_lossy(&values[lo..hi]));
                } else {
                    b.append_null();
                }
            }
            Arc::new(b.finish())
        }
        _ => Arc::new(arrow::array::NullArray::new(col.len())),
    })
}

fn bit_set(validity: &[u8], i: usize) -> bool {
    (validity.get(i / 8).copied().unwrap_or(0) >> (i % 8)) & 1 == 1
}

fn validity_to_nulls(validity: &[u8], n: usize) -> Option<arrow::buffer::NullBuffer> {
    let all_set = (0..n).all(|i| bit_set(validity, i));
    if all_set {
        return None;
    }
    let bools: Vec<bool> = (0..n).map(|i| bit_set(validity, i)).collect();
    Some(arrow::buffer::NullBuffer::from(bools))
}

// ── Phase 19.4: Remote (daemon-backed) Database ───────────────────────────

/// A daemon-backed database connection (Phase 19.4). Routes put/get/count/
/// query/commit to a `mongreldb-server` instance over HTTP. Multiple Node
/// processes can share one warm cache this way.
#[napi]
pub struct RemoteDatabase {
    url: String,
    agent: ureq::Agent,
}

#[napi]
impl RemoteDatabase {
    /// Connect to a `mongreldb-server` at `url` (e.g. `http://127.0.0.1:8453`).
    #[napi(constructor)]
    pub fn connect(url: String) -> napi::Result<RemoteDatabase> {
        Ok(RemoteDatabase {
            url: url.trim_end_matches('/').to_string(),
            agent: ureq::Agent::new(),
        })
    }

    #[napi]
    pub fn health(&self) -> napi::Result<String> {
        self.agent
            .get(&format!("{}/health", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_string()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
    }

    #[napi]
    pub fn table_names(&self) -> napi::Result<Vec<String>> {
        self.agent
            .get(&format!("{}/tables", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_json()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
    }

    #[napi]
    pub fn count(&self, table: String) -> napi::Result<f64> {
        let resp: serde_json::Value = self
            .agent
            .get(&format!("{}/tables/{table}/count", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_json()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(resp["count"].as_f64().unwrap_or(0.0))
    }

    #[napi]
    pub fn sql(&self, sql: String) -> napi::Result<Buffer> {
        let resp = self
            .agent
            .post(&format!("{}/sql", self.url))
            .send_json(serde_json::json!({ "sql": sql }))
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        let bytes = resp
            .into_string()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(Buffer::from(bytes.into_bytes()))
    }

    #[napi]
    pub fn commit(&self, table: String) -> napi::Result<BigInt> {
        let resp: serde_json::Value = self
            .agent
            .post(&format!("{}/tables/{table}/commit", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_json()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(BigInt::from(resp["epoch"].as_u64().unwrap_or(0)))
    }
}

// ── Phase 20.4 helpers ────────────────────────────────────────────────────

fn native_cols_to_ipc(
    cols: &[(u16, mongreldb_core::columnar::NativeColumn)],
    schema: &mongreldb_core::schema::Schema,
) -> napi::Result<Vec<u8>> {
    let fields: Vec<arrow::datatypes::Field> = cols
        .iter()
        .map(|(id, col)| {
            let dt = match col {
                mongreldb_core::columnar::NativeColumn::Int64 { .. } => {
                    arrow::datatypes::DataType::Int64
                }
                mongreldb_core::columnar::NativeColumn::Float64 { .. } => {
                    arrow::datatypes::DataType::Float64
                }
                mongreldb_core::columnar::NativeColumn::Bool { .. } => {
                    arrow::datatypes::DataType::Boolean
                }
                mongreldb_core::columnar::NativeColumn::Bytes { .. } => {
                    arrow::datatypes::DataType::Utf8
                }
            };
            let name = schema
                .columns
                .iter()
                .find(|c| c.id == *id)
                .map(|c| c.name.as_str())
                .unwrap_or("col");
            arrow::datatypes::Field::new(name, dt, true)
        })
        .collect();
    let arrow_schema = std::sync::Arc::new(arrow::datatypes::Schema::new(fields));
    let arrays: Vec<arrow::array::ArrayRef> = cols
        .iter()
        .map(|(id, col)| {
            let ty = schema
                .columns
                .iter()
                .find(|c| c.id == *id)
                .map(|c| c.ty)
                .unwrap_or(mongreldb_core::schema::TypeId::Bytes);
            arrow_from_native(ty, col)
        })
        .collect::<napi::Result<Vec<_>>>()?;
    let batch = arrow::record_batch::RecordBatch::try_new(arrow_schema, arrays)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let mut buf = Vec::new();
    {
        let mut writer = arrow::ipc::writer::FileWriter::try_new(&mut buf, batch.schema().as_ref())
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        let _ = writer.write(&batch);
        let _ = writer.finish();
    }
    Ok(buf)
}
