//! Native Node.js addon for MongrelDB via NAPI — the better-sqlite3 model:
//! in-process, zero-HTTP-latency, sub-millisecond single-row writes.
//!
//! This crate exposes a **typed object/method interface** (not SQL): `Database`,
//! `put`, `get`, `commit`, `flush`, `count`, and a hybrid `query` that composes
//! the six row-id-space index primitives. TypeScript types are generated by
//! `@napi-rs/cli` at build time (`napi build`).
//!
//! Build (requires Node.js + `@napi-rs/cli`):
//!   cd crates/mongreldb-node && napi build --release --platform
//! Produces `mongreldb.<platform>.node` + `index.d.ts`.
//!
//! NOTE: row ids / counts / epochs cross the FFI as `u32`/`i32` (JS Number).
//! Swap to `BigInt` (napi `i64`/`u64`) for tables beyond 2³² rows or full i64
//! ranges — a localized change to the types in this file.

#![deny(clippy::all)]

use mongreldb_core::query::{Condition, Query};
use mongreldb_core::schema::{ColumnDef, ColumnFlags, IndexDef, IndexKind, Schema, TypeId};
use mongreldb_core::{RowId, Value};
use napi::bindgen_prelude::{BigInt, Buffer};
use napi_derive::napi;
use std::sync::Arc;

fn to_napi(e: mongreldb_core::MongrelError) -> napi::Error {
    napi::Error::new(napi::Status::GenericFailure, format!("{e:?}"))
}

// ── schema ────────────────────────────────────────────────────────────────

#[napi]
pub enum ColumnType {
    Bool,
    Int64,
    Float64,
    TimestampNanos,
    Date32,
    Bytes,
    Embedding,
}

#[napi]
pub enum IndexKindSpec {
    Bitmap,
    FmIndex,
    Ann,
}

#[napi(object)]
pub struct ColumnSpec {
    pub id: u16,
    pub name: String,
    pub ty: ColumnType,
    pub primary_key: bool,
    pub nullable: bool,
    /// Required when `ty == Embedding`.
    pub embedding_dim: Option<u32>,
}

#[napi(object)]
pub struct IndexSpec {
    pub name: String,
    pub column_id: u16,
    pub kind: IndexKindSpec,
}

#[napi(object)]
pub struct SchemaSpec {
    pub columns: Vec<ColumnSpec>,
    pub indexes: Vec<IndexSpec>,
}

fn to_type_id(ty: &ColumnType, embedding_dim: Option<u32>) -> napi::Result<TypeId> {
    Ok(match ty {
        ColumnType::Bool => TypeId::Bool,
        ColumnType::Int64 => TypeId::Int64,
        ColumnType::Float64 => TypeId::Float64,
        ColumnType::TimestampNanos => TypeId::TimestampNanos,
        ColumnType::Date32 => TypeId::Date32,
        ColumnType::Bytes => TypeId::Bytes,
        ColumnType::Embedding => TypeId::Embedding {
            dim: embedding_dim.ok_or_else(|| {
                napi::Error::new(
                    napi::Status::InvalidArg,
                    "embedding_dim is required for Embedding columns",
                )
            })?,
        },
    })
}

fn build_schema(spec: SchemaSpec) -> napi::Result<Schema> {
    let columns = spec
        .columns
        .into_iter()
        .map(|c| {
            let mut f = ColumnFlags::empty();
            if c.primary_key {
                f = f.with(ColumnFlags::PRIMARY_KEY);
            }
            if c.nullable {
                f = f.with(ColumnFlags::NULLABLE);
            }
            Ok::<ColumnDef, napi::Error>(ColumnDef {
                id: c.id,
                name: c.name,
                ty: to_type_id(&c.ty, c.embedding_dim)?,
                flags: f,
            })
        })
        .collect::<napi::Result<Vec<_>>>()?;
    let indexes = spec
        .indexes
        .into_iter()
        .map(|i| IndexDef {
            name: i.name,
            column_id: i.column_id,
            kind: match i.kind {
                IndexKindSpec::Bitmap => IndexKind::Bitmap,
                IndexKindSpec::FmIndex => IndexKind::FmIndex,
                IndexKindSpec::Ann => IndexKind::Ann,
            },
        })
        .collect();
    Ok(Schema {
        schema_id: 1,
        columns,
        indexes,
        colocation: Vec::new(),
    })
}

// ── values ────────────────────────────────────────────────────────────────

/// A single cell value. Only the field matching the column type is read; the
/// rest are ignored. `bytes` is raw; `text` is UTF-8 (use for `Bytes` columns
/// when the value is a string).
#[napi(object)]
pub struct Cell {
    pub column_id: u16,
    pub int64: Option<i32>,
    pub float64: Option<f64>,
    pub boolean: Option<bool>,
    pub text: Option<String>,
    pub bytes: Option<Buffer>,
    pub embedding: Option<Vec<f64>>,
}

impl Cell {
    fn empty(column_id: u16) -> Self {
        Self {
            column_id,
            int64: None,
            float64: None,
            boolean: None,
            text: None,
            bytes: None,
            embedding: None,
        }
    }

    fn to_value(&self, ty: TypeId) -> Value {
        match ty {
            TypeId::Bool => Value::Bool(self.boolean.unwrap_or(false)),
            TypeId::Int64 | TypeId::TimestampNanos | TypeId::Date32 => {
                Value::Int64(self.int64.unwrap_or(0) as i64)
            }
            TypeId::Float64 => Value::Float64(self.float64.unwrap_or(0.0)),
            TypeId::Bytes => match &self.text {
                Some(s) => Value::Bytes(s.as_bytes().to_vec()),
                None => Value::Bytes(self.bytes.as_ref().map(|b| b.to_vec()).unwrap_or_default()),
            },
            TypeId::Embedding { .. } => {
                Value::Embedding(self.embedding.iter().flatten().map(|x| *x as f32).collect())
            }
            _ => Value::Null,
        }
    }
}

fn from_value(v: &Value, column_id: u16) -> Cell {
    let mut cell = Cell::empty(column_id);
    match v {
        Value::Null => {}
        Value::Bool(b) => cell.boolean = Some(*b),
        Value::Int64(n) => cell.int64 = Some(*n as i32),
        Value::Float64(f) => cell.float64 = Some(*f),
        Value::Bytes(b) => match std::str::from_utf8(b) {
            Ok(s) => cell.text = Some(s.to_string()),
            Err(_) => cell.bytes = Some(Buffer::from(b.clone())),
        },
        Value::Embedding(e) => cell.embedding = Some(e.iter().map(|x| *x as f64).collect()),
    }
    cell
}

// ── query conditions ──────────────────────────────────────────────────────

#[napi]
pub enum ConditionKind {
    Pk,
    BitmapEq,
    RangeInt,
    RangeF64,
    FmContains,
    Ann,
}

/// One predicate over the shared row-id space. Set the fields appropriate to
/// `kind`; unused fields are ignored. A `query` takes a conjunction (AND) of
/// these — the differentiator no SQL FTS pipeline can match.
#[napi(object)]
pub struct ConditionSpec {
    pub kind: ConditionKind,
    pub column_id: u16,
    pub int64_lo: Option<i32>,
    pub int64_hi: Option<i32>,
    pub float64_lo: Option<f64>,
    pub float64_hi: Option<f64>,
    pub text: Option<String>,
    pub embedding: Option<Vec<f64>>,
    pub k: Option<u32>,
}

fn build_condition(spec: &ConditionSpec) -> napi::Result<Condition> {
    Ok(match spec.kind {
        ConditionKind::Pk => Condition::Pk(text_bytes(spec)?),
        ConditionKind::BitmapEq => Condition::BitmapEq {
            column_id: spec.column_id,
            value: text_bytes(spec)?,
        },
        ConditionKind::RangeInt => Condition::Range {
            column_id: spec.column_id,
            lo: spec.int64_lo.unwrap_or(i32::MIN) as i64,
            hi: spec.int64_hi.unwrap_or(i32::MAX) as i64,
        },
        ConditionKind::RangeF64 => Condition::RangeF64 {
            column_id: spec.column_id,
            lo: spec.float64_lo.unwrap_or(f64::NEG_INFINITY),
            lo_inclusive: true,
            hi: spec.float64_hi.unwrap_or(f64::INFINITY),
            hi_inclusive: true,
        },
        ConditionKind::FmContains => Condition::FmContains {
            column_id: spec.column_id,
            pattern: text_bytes(spec)?,
        },
        ConditionKind::Ann => Condition::Ann {
            column_id: spec.column_id,
            query: spec
                .embedding
                .clone()
                .ok_or_else(|| napi::Error::new(napi::Status::InvalidArg, "Ann needs embedding"))?
                .iter()
                .map(|x| *x as f32)
                .collect(),
            k: spec.k.unwrap_or(10) as usize,
        },
    })
}

fn text_bytes(spec: &ConditionSpec) -> napi::Result<Vec<u8>> {
    spec.text
        .as_ref()
        .map(|s| s.as_bytes().to_vec())
        .ok_or_else(|| napi::Error::new(napi::Status::InvalidArg, "expected `text`"))
}

#[napi(object)]
pub struct RowJs {
    pub row_id: BigInt,
    pub cells: Vec<Cell>,
}

// ── multi-table Database + Table (P5.1) ───────────────────────────────────

use mongreldb_core::Database as CoreDatabase;

/// An open MongrelDB multi-table database. Each table is accessible via
/// `table(name)`; SQL queries via `sql()`.
#[napi]
pub struct Database {
    inner: Arc<CoreDatabase>,
}

/// A handle to one table inside a [`Database`].
#[napi]
pub struct TableHandle {
    db: Arc<CoreDatabase>,
    table_id: u64,
    name: String,
}

fn cell_pairs_table(
    t: &mongreldb_core::Table,
    cells: Vec<Cell>,
) -> napi::Result<Vec<(u16, Value)>> {
    let schema = t.schema();
    cells
        .into_iter()
        .map(|c| {
            let ty = schema
                .columns
                .iter()
                .find(|cd| cd.id == c.column_id)
                .map(|cd| cd.ty)
                .unwrap_or(TypeId::Bytes);
            Ok((c.column_id, c.to_value(ty)))
        })
        .collect()
}

fn row_to_js_table(t: &mongreldb_core::Table, row: &mongreldb_core::memtable::Row) -> RowJs {
    let schema = t.schema();
    let cells = schema
        .columns
        .iter()
        .map(|cd| {
            let v = row.columns.get(&cd.id).cloned().unwrap_or(Value::Null);
            from_value(&v, cd.id)
        })
        .collect();
    RowJs {
        row_id: BigInt::from(row.row_id.0),
        cells,
    }
}

#[napi]
impl Database {
    /// Create a fresh database at `path`.
    #[napi(factory)]
    pub fn with_path(path: String) -> napi::Result<Database> {
        let db = CoreDatabase::create(&path).map_err(to_napi)?;
        Ok(Database {
            inner: Arc::new(db),
        })
    }

    /// Open an existing database from disk.
    #[napi]
    pub fn open(path: String) -> napi::Result<Database> {
        let db = CoreDatabase::open(&path).map_err(to_napi)?;
        Ok(Database {
            inner: Arc::new(db),
        })
    }

    /// Create a new table with the given schema.
    #[napi]
    pub fn create_table(&self, name: String, schema: SchemaSpec) -> napi::Result<BigInt> {
        let s = build_schema(schema)?;
        let id = self.inner.create_table(&name, s).map_err(to_napi)?;
        Ok(BigInt::from(id))
    }

    /// Drop a table by name.
    #[napi]
    pub fn drop_table(&self, name: String) -> napi::Result<()> {
        self.inner.drop_table(&name).map_err(to_napi)
    }

    /// Get a handle to a table by name for typed put/get/query operations.
    #[napi]
    pub fn get_table(&self, name: String) -> napi::Result<TableHandle> {
        let table_id = self.inner.table_id(&name).map_err(to_napi)?;
        Ok(TableHandle {
            db: Arc::clone(&self.inner),
            table_id,
            name,
        })
    }

    /// List all live table names.
    #[napi]
    pub fn table_names(&self) -> Vec<String> {
        self.inner.table_names()
    }

    /// Run a cross-table SQL query. Returns Arrow IPC bytes.
    #[napi]
    pub async fn sql(&self, sql: String) -> napi::Result<Buffer> {
        let db = Arc::clone(&self.inner);
        let session = mongreldb_query::MongrelSession::open(db)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
        let batches = session
            .run(&sql)
            .await
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
        native_cols_to_ipc_from_batches(&batches)
    }

    /// Flush + release. Optional — the `Database` also drops on GC.
    #[napi]
    pub fn close(&self) -> napi::Result<()> {
        Ok(())
    }
}

fn native_cols_to_ipc_from_batches(
    batches: &[arrow::record_batch::RecordBatch],
) -> napi::Result<Buffer> {
    if batches.is_empty() {
        return Ok(Buffer::from(Vec::new()));
    }
    let schema = batches[0].schema();
    let mut buf = Vec::new();
    let mut writer = arrow::ipc::writer::FileWriter::try_new(&mut buf, schema.as_ref())
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
    for b in batches {
        writer
            .write(b)
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
    }
    writer
        .finish()
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?;
    drop(writer);
    Ok(Buffer::from(buf))
}

#[napi]
impl TableHandle {
    /// Upsert one row. Returns the row id.
    #[napi]
    pub fn put(&self, cells: Vec<Cell>) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let cols = cell_pairs_table(&g, cells)?;
        let rid = g.put(cols).map_err(to_napi)?;
        Ok(BigInt::from(rid.0))
    }

    /// Group-commit this table's pending writes.
    #[napi]
    pub fn commit(&self) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.commit().map(|e| BigInt::from(e.0)).map_err(to_napi)
    }

    /// Flush: commit + drain memtable to a sorted run.
    #[napi]
    pub fn flush(&self) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.flush().map(|e| BigInt::from(e.0)).map_err(to_napi)
    }

    /// Live row count (O(1)).
    #[napi]
    pub fn count(&self) -> napi::Result<BigInt> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let g = handle.lock();
        Ok(BigInt::from(g.count()))
    }

    /// Point read by row id.
    #[napi]
    pub fn get(&self, row_id: BigInt) -> napi::Result<Option<RowJs>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let g = handle.lock();
        let snap = g.snapshot();
        Ok(g.get(RowId(row_id.get_u64().1), snap)
            .map(|r| row_to_js_table(&g, &r)))
    }

    /// Hybrid index query.
    #[napi]
    pub fn query(&self, conditions: Vec<ConditionSpec>) -> napi::Result<Vec<RowJs>> {
        let handle = self.db.table(&self.name).map_err(to_napi)?;
        let mut g = handle.lock();
        let mut q = Query::new();
        for c in &conditions {
            q = q.and(build_condition(c)?);
        }
        let rows = g.query_cached(&q).map_err(to_napi)?;
        Ok(rows.iter().map(|r| row_to_js_table(&g, r)).collect())
    }

    // ── async variants ──

    #[napi]
    pub async fn put_async(&self, cells: Vec<Cell>) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<BigInt> {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            let cols = cell_pairs_table(&g, cells)?;
            let rid = g.put(cols).map_err(to_napi)?;
            Ok(BigInt::from(rid.0))
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn commit_async(&self) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            g.commit().map(|e| BigInt::from(e.0)).map_err(to_napi)
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn count_async(&self) -> napi::Result<BigInt> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || {
            let handle = db.table(&name).map_err(to_napi)?;
            let g = handle.lock();
            Ok(BigInt::from(g.count()))
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn get_async(&self, row_id: BigInt) -> napi::Result<Option<RowJs>> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<Option<RowJs>> {
            let handle = db.table(&name).map_err(to_napi)?;
            let g = handle.lock();
            let snap = g.snapshot();
            Ok(g.get(RowId(row_id.get_u64().1), snap)
                .map(|r| row_to_js_table(&g, &r)))
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }

    #[napi]
    pub async fn query_async(&self, conditions: Vec<ConditionSpec>) -> napi::Result<Vec<RowJs>> {
        let db = Arc::clone(&self.db);
        let name = self.name.clone();
        napi::bindgen_prelude::spawn_blocking(move || -> napi::Result<Vec<RowJs>> {
            let handle = db.table(&name).map_err(to_napi)?;
            let mut g = handle.lock();
            let mut q = Query::new();
            for c in &conditions {
                q = q.and(build_condition(c)?);
            }
            let rows = g.query_cached(&q).map_err(to_napi)?;
            Ok(rows.iter().map(|r| row_to_js_table(&g, r)).collect())
        })
        .await
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, format!("{e:?}")))?
    }
}

/// Phase 20.2: a typed column for bulk loading, wrapping JS typed-array data.
#[napi(object)]
pub struct TypedColumn {
    pub column_id: u16,
    pub ty: ColumnType,
    /// Raw data bytes (Int64 = N×8 LE, Float64 = N×8 LE, Bytes = N+1 offsets + values).
    pub data: Buffer,
    /// Optional validity bitmap (1 byte per row, 1=non-null).
    pub validity: Option<Buffer>,
}

impl TypedColumn {
    fn to_native(self) -> napi::Result<(u16, mongreldb_core::columnar::NativeColumn)> {
        let n = match self.ty {
            ColumnType::Int64
            | ColumnType::Float64
            | ColumnType::TimestampNanos
            | ColumnType::Date32 => self.data.len() / 8,
            ColumnType::Bool => self.data.len(),
            ColumnType::Bytes | ColumnType::Embedding => {
                return Err(napi::Error::new(
                    napi::Status::InvalidArg,
                    "Bytes/Embedding columns not supported in bulk_load_typed; use bulk_load",
                ))
            }
        };
        let validity = self
            .validity
            .map(|b| b.to_vec())
            .unwrap_or_else(|| vec![0xFF; n.div_ceil(8)]);
        let col = match self.ty {
            ColumnType::Int64 | ColumnType::TimestampNanos | ColumnType::Date32 => {
                let data = bytemuck::cast_slice::<_, i64>(&self.data).to_vec();
                mongreldb_core::columnar::NativeColumn::Int64 { data, validity }
            }
            ColumnType::Float64 => {
                let data = bytemuck::cast_slice::<_, f64>(&self.data).to_vec();
                mongreldb_core::columnar::NativeColumn::Float64 { data, validity }
            }
            ColumnType::Bool => mongreldb_core::columnar::NativeColumn::Bool {
                data: self.data.to_vec(),
                validity,
            },
            _ => unreachable!(),
        };
        Ok((self.column_id, col))
    }
}

/// Opt-in write micro-batching over one table. Writes are **not durable until
/// flush** — the contract is the opposite of `put()`.
#[napi]
pub struct WriteBuffer {
    db: Arc<CoreDatabase>,
    table_name: String,
    buffer: Vec<Vec<(u16, Value)>>,
    threshold: usize,
}

#[napi]
impl WriteBuffer {
    /// Create a new WriteBuffer over a table. `threshold` rows trigger an auto-flush.
    #[napi(constructor)]
    pub fn new(table: &TableHandle, threshold: Option<u32>) -> Self {
        Self {
            db: Arc::clone(&table.db),
            table_name: table.name.clone(),
            buffer: Vec::new(),
            threshold: threshold.unwrap_or(1000) as usize,
        }
    }

    /// Buffer a write (not durable until `flush`). Auto-flushes when the
    /// threshold is reached, returning the new row id.
    #[napi]
    pub fn put(&mut self, cells: Vec<Cell>) -> napi::Result<Option<BigInt>> {
        let pair = {
            let handle = self.db.table(&self.table_name).map_err(to_napi)?;
            let g = handle.lock();
            cell_pairs_table(&g, cells)?
        };
        self.buffer.push(pair);
        if self.buffer.len() >= self.threshold {
            let n = self.flush()?;
            Ok(Some(n))
        } else {
            Ok(None)
        }
    }

    /// Flush all buffered writes (durable after this call). Returns the new epoch.
    #[napi]
    pub fn flush(&mut self) -> napi::Result<BigInt> {
        if self.buffer.is_empty() {
            let handle = self.db.table(&self.table_name).map_err(to_napi)?;
            return Ok(BigInt::from(handle.lock().current_epoch().0));
        }
        let batch = std::mem::take(&mut self.buffer);
        let handle = self.db.table(&self.table_name).map_err(to_napi)?;
        let mut g = handle.lock();
        g.put_batch(batch).map_err(to_napi)?;
        let epoch = g.commit().map_err(to_napi)?;
        Ok(BigInt::from(epoch.0))
    }
}

fn arrow_from_native(
    ty: mongreldb_core::schema::TypeId,
    col: &mongreldb_core::columnar::NativeColumn,
) -> napi::Result<arrow::array::ArrayRef> {
    use mongreldb_core::columnar::NativeColumn;
    use mongreldb_core::schema::TypeId;
    Ok(match (ty, col) {
        (
            TypeId::Int64 | TypeId::TimestampNanos | TypeId::Date32,
            NativeColumn::Int64 { data, validity },
        ) => {
            let buf: arrow::buffer::ScalarBuffer<_> = data.clone().into();
            let nulls = validity_to_nulls(validity, data.len());
            Arc::new(arrow::array::Int64Array::new(buf, nulls))
        }
        (TypeId::Float64, NativeColumn::Float64 { data, validity }) => {
            let buf: arrow::buffer::ScalarBuffer<_> = data.clone().into();
            let nulls = validity_to_nulls(validity, data.len());
            Arc::new(arrow::array::Float64Array::new(buf, nulls))
        }
        (TypeId::Bool, NativeColumn::Bool { data, validity }) => {
            let mut b = arrow::array::BooleanBuilder::with_capacity(data.len());
            for (i, &v) in data.iter().enumerate() {
                if bit_set(validity, i) {
                    b.append_value(v != 0);
                } else {
                    b.append_null();
                }
            }
            Arc::new(b.finish())
        }
        (
            _,
            NativeColumn::Bytes {
                offsets,
                values,
                validity,
            },
        ) => {
            let n = offsets.len().saturating_sub(1);
            let mut b = arrow::array::StringBuilder::with_capacity(n, values.len());
            for i in 0..n {
                if bit_set(validity, i) {
                    let lo = offsets[i] as usize;
                    let hi = offsets[i + 1] as usize;
                    b.append_value(String::from_utf8_lossy(&values[lo..hi]));
                } else {
                    b.append_null();
                }
            }
            Arc::new(b.finish())
        }
        _ => Arc::new(arrow::array::NullArray::new(col.len())),
    })
}

fn bit_set(validity: &[u8], i: usize) -> bool {
    (validity.get(i / 8).copied().unwrap_or(0) >> (i % 8)) & 1 == 1
}

fn validity_to_nulls(validity: &[u8], n: usize) -> Option<arrow::buffer::NullBuffer> {
    let all_set = (0..n).all(|i| bit_set(validity, i));
    if all_set {
        return None;
    }
    let bools: Vec<bool> = (0..n).map(|i| bit_set(validity, i)).collect();
    Some(arrow::buffer::NullBuffer::from(bools))
}

// ── Phase 19.4: Remote (daemon-backed) Database ───────────────────────────

/// A daemon-backed database connection (Phase 19.4). Routes put/get/count/
/// query/commit to a `mongreldb-server` instance over HTTP. Multiple Node
/// processes can share one warm cache this way.
#[napi]
pub struct RemoteDatabase {
    url: String,
    agent: ureq::Agent,
}

#[napi]
impl RemoteDatabase {
    /// Connect to a `mongreldb-server` at `url` (e.g. `http://127.0.0.1:8453`).
    #[napi(constructor)]
    pub fn connect(url: String) -> napi::Result<RemoteDatabase> {
        Ok(RemoteDatabase {
            url: url.trim_end_matches('/').to_string(),
            agent: ureq::Agent::new(),
        })
    }

    /// Check daemon health.
    #[napi]
    pub fn health(&self) -> napi::Result<String> {
        self.agent
            .get(&format!("{}/health", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_string()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))
    }

    /// Get the live row count (O(1) on the daemon side).
    #[napi]
    pub fn count(&self) -> napi::Result<f64> {
        let resp: serde_json::Value = self
            .agent
            .get(&format!("{}/count", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_json()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(resp["count"].as_f64().unwrap_or(0.0))
    }

    /// Run a SQL query and return Arrow IPC bytes.
    #[napi]
    pub fn sql(&self, sql: String) -> napi::Result<Buffer> {
        let resp = self
            .agent
            .post(&format!("{}/sql", self.url))
            .send_json(serde_json::json!({ "sql": sql }))
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        let bytes = resp
            .into_string()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(Buffer::from(bytes.into_bytes()))
    }

    /// Commit pending writes.
    #[napi]
    pub fn commit(&self) -> napi::Result<BigInt> {
        let resp: serde_json::Value = self
            .agent
            .post(&format!("{}/commit", self.url))
            .call()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?
            .into_json()
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(BigInt::from(resp["epoch"].as_u64().unwrap_or(0)))
    }
}

// ── Phase 20.4 helpers ────────────────────────────────────────────────────

fn native_cols_to_ipc(
    cols: &[(u16, mongreldb_core::columnar::NativeColumn)],
    schema: &mongreldb_core::schema::Schema,
) -> napi::Result<Vec<u8>> {
    let fields: Vec<arrow::datatypes::Field> = cols
        .iter()
        .map(|(id, col)| {
            let dt = match col {
                mongreldb_core::columnar::NativeColumn::Int64 { .. } => {
                    arrow::datatypes::DataType::Int64
                }
                mongreldb_core::columnar::NativeColumn::Float64 { .. } => {
                    arrow::datatypes::DataType::Float64
                }
                mongreldb_core::columnar::NativeColumn::Bool { .. } => {
                    arrow::datatypes::DataType::Boolean
                }
                mongreldb_core::columnar::NativeColumn::Bytes { .. } => {
                    arrow::datatypes::DataType::Utf8
                }
            };
            let name = schema
                .columns
                .iter()
                .find(|c| c.id == *id)
                .map(|c| c.name.as_str())
                .unwrap_or("col");
            arrow::datatypes::Field::new(name, dt, true)
        })
        .collect();
    let arrow_schema = std::sync::Arc::new(arrow::datatypes::Schema::new(fields));
    let arrays: Vec<arrow::array::ArrayRef> = cols
        .iter()
        .map(|(id, col)| {
            let ty = schema
                .columns
                .iter()
                .find(|c| c.id == *id)
                .map(|c| c.ty)
                .unwrap_or(mongreldb_core::schema::TypeId::Bytes);
            arrow_from_native(ty, col)
        })
        .collect::<napi::Result<Vec<_>>>()?;
    let batch = arrow::record_batch::RecordBatch::try_new(arrow_schema, arrays)
        .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
    let mut buf = Vec::new();
    {
        let mut writer = arrow::ipc::writer::FileWriter::try_new(&mut buf, batch.schema().as_ref())
            .map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        let _ = writer.write(&batch);
        let _ = writer.finish();
    }
    Ok(buf)
}
